### GET /
GET http://localhost:5000/

### Register a user POST /auth/register 
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "hot@gmail.com",
    "password": "123123123"
}

### Log in a user POST /auth/login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "hot@gmail.com",
    "password": "123123123"
}

### Fetch todos GET /todos (protected)
GET http://localhost:5000/todos
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0MjM1Nzk1LCJleHAiOjE3NjQzMjIxOTV9.3uVyjXuSkBisyRWmIKMIERDTRYsgd_GlKLVAkX0o4Qs

### Create a new todo POST /todos (protected)
POST http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0MjM1Nzk1LCJleHAiOjE3NjQzMjIxOTV9.3uVyjXuSkBisyRWmIKMIERDTRYsgd_GlKLVAkX0o4Qs
Content-Type: application/json

{
    "task": "hi"
}

### Update a todo PUT /todos/:id (protected)
PUT http://localhost:5000/todos/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0MjM1Nzk1LCJleHAiOjE3NjQzMjIxOTV9.3uVyjXuSkBisyRWmIKMIERDTRYsgd_GlKLVAkX0o4Qs
Content-Type: application/json

{
    "completed": 1
}

### Delete a todo DELETE /todos/:id (protected)
DELETE http://localhost:5000/todos/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0MjM1Nzk1LCJleHAiOjE3NjQzMjIxOTV9.3uVyjXuSkBisyRWmIKMIERDTRYsgd_GlKLVAkX0o4Qs
