### TEST GET
GET http://localhost:3001/

### TEST GET / dashboard
GET http://localhost:3001/dashboard

### data endpoint
GET http://localhost:3001/api/data/

### data endpoint for adding a user
POST http://localhost:3001/api/data/
Content-Type: application/json

{
    "name": "mumbai"
}

### Deleting a user
DELETE http://localhost:3001/api/data/